---
version: "2.1"
services:
  elk:
    build: .
    image: elk:latest
    container_name: elk
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    ports:
      - 9200:9200
      - 5601:5601
    restart: unless-stopped
